permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Zhiyu Jiang
  email: jzhiyu1991@gmail.com
  link: http://zhiyu-jiang.github.io/
  weibo: http://weibo.com/jzhiyu
  github: http://github.com/zhiyu-jiang
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: Zhiyu Jiang's Personal Homepage
description: personal homepage
url: http://zhiyu-jiang.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/cat.jpg
favicon: /public/img/cat.jpg

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: jiangzhiyu

# 主题设置，自动激活某个标签
active: Life

# 首页除了最新文章外显示分类
cates: 
  - 摄影
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新
  archive: 存档